import Navbar from "@/components/Navbar";
import "./globals.css";
import { Roboto } from "@next/font/google";
import localFont from 'next/font/local'

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"   className={`${roboto.variable} `} >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
